name: Main workflow
on: [push]
jobs:
  things:
    runs-on: windows-latest
    steps:
      - shell: powershell
        run: |
          dir $env:WIX
          echo $env:WIX
        # run: |
        #   where.exe heat
        #   where.exe candle
        #   where.exe light
