name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: zlib
      - uses: haskell-CI/setup@main
        with:
          ghc-version: 8.8.4
          cabal-version: 3.2.0.0

      - shell: msys2 {0}
        run: cabal update
        continue-on-error: true
      - shell: powershell
        run: cabal update
        continue-on-error: true

      - shell: msys2 {0}
        run: cabal run
        continue-on-error: true
      - shell: powershell
        run: cabal run
        continue-on-error: true

      - run: choco install -y cabal --reinstall --force
      - run: refreshenv
      - run: mingw64-pkg install zlib || pacman -Sy mingw-w64-x86_64-zlib
        continue-on-error: true

      - shell: msys2 {0}
        run: cabal run
        continue-on-error: true
      - shell: powershell
        run: cabal run
        continue-on-error: true
