name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: tst
          key: wew-lad
      - run: |
          mkdir tst
          echo hello world > tst/foo.bleh
  wat2:
    needs: [wat]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: tst
          key: wew-lad
      - run: cat tst/foo.bleh
