name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/action
        with:
          ssh-key: some key or something
