name: Main workflow
on: [push]
jobs:
  test:
    name: Test windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: .setup-haskell
          key: ghc
      - uses: haskell-ci/setup@add-windows-cache
        with:
          ghc-version: 8.4.4
          cabal-version: 3.0.0.0
      - run: |
          cabal user-config update
          cabal update
      - run: |
          ls C:\ProgramData\chocolatey\lib\ghc.8.4.4\tools
          get-command cabal -or $true
          get-command ghc -or $true
      - run: cabal build
      - run: |
          ls $env:APPDATA\cabal
          ls $HOME
        shell: pwsh
