name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        array-a: [1, 2, 3, 4, 5]
        array-b: [1, 2, 3]
        idx: [a, b]
    steps:
      - run: echo "${{ matrix.idx }}"
      - run: echo "${{ matrix.array-a }}"
      - run: echo "${{ matrix.array-b }}"
      - run: echo "${{ matrix.array-${{ matrix.idx }} }}"
