name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: matrix.cfg.host
    strategy:
      matrix:
        cfg:
          - { a: 1, b: 1, c: 1, host: self-hosted }
          - { a: 2, b: 2, c: 2, host: self-hosted }
          - { a: 3, b: 3, c: 3, host: self-hosted }
          - { a: 4, b: 4, c: 4, host: self-hosted }
          - { a: 5, b: 5, c: 5, host: self-hosted }
          - { a: 6, b: 6, c: 6, host: self-hosted }
    steps:
      - run: echo "${{ matrix.cfg.a }}"
      - run: echo "${{ matrix.cfg.b }}"
      - run: echo "${{ matrix.cfg.c }}"
