name: Test Nightly
on: [push, pull_request]

jobs:
  outputs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          foo: blah
        run: powershell .github/test.ps1
      - env:
          foo: blah
        run: .github\test.ps1
