name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: ubuntu-latest
    steps:
      - run: |
          hub release show v2.9.0
          if hub release show v2.9.0; then
            echo "howdy"
          else
            echo "making release"
            hub release create -d v2.9.0
          fi
