name: Test things
on:
  push:
    tags:
      - "v**"
    branches:
      - master
      - "new-*"
  pull_request:

jobs:
  wat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.base_ref }} ${{ github.head_ref }}
