name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-haskell@v1
        with:
          ghc: 8.10.2
          cabal: 3.4.0.0
      - run: pacman -Sy mingw-w64-x86_64-zlib
