name: Main workflow
on: [push]
jobs:
  test:
    name: Test windows
    runs-on: windows-latest
    steps:
      - shell: powershell
        run: |
          Get-PSRepository

# Install-Module -Name ghcups
# Import-Module ghcups
# Get-Module ghcups
# Get-Help -Full Install-Ghc
# Install-Ghc 8.8.3
