name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: zlib
      - uses: haskell-CI/setup@main
        with:
          ghc-version: 8.8.4
          cabal-version: 3.2.0.0
      - run: cabal update
      - run: cabal run
