name: Test things
on: [push, pull_request]

jobs:
  wat:
    runs-on: windows-latest
    steps:
      - uses: haskell-CI/setup@main
        with:
          ghc-version: 8.10.2
          cabal-version: 3.2.0.0
      - run: choco install -y msys2
      - run: refreshenv
      - run: mingw64-pkg zlib || pacman -Sy mingw-w64-x86_64-zlib
