name: Main workflow
on: [push]
jobs:
  test:
    name: Test windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: $HOME\.setup-haskell
          key: ghc
      - uses: haskell-ci/setup@add-windows-cache
        with:
          ghc-version: 8.8.3
          cabal-version: 3.0.0.0
      - run: |
          cabal user-config update
      - run: cabal build
      - run: |
          ls $env:APPDATA
        shell: pwsh
