name: Main workflow
on: [push]
jobs:
  things:
    runs-on: windows-latest
    steps:
      - shell: powershell
        run: |
          dir $env:WIX\bin
          echo $env:WIX
  # ${HEAT} dir ${PKG_PREFIX} -o allfiles.wxs -nologo -var var.pkg \
  #         -ag -wixvar -cg ALLFILES -srd -dr INSTALLDIR -sfrag
  #
  #
  # ${CANDLE} -ext WixUIExtension -ext WixUtilExtension            \
  #         -dversion=${VERSION} -dpkg=${PKG_PREFIX} win32/cryptol.wxs
  #
  # ${CANDLE} -ext WixUIExtension -ext WixUtilExtension            \
  #         -dversion=${VERSION} -dpkg=${PKG_PREFIX} allfiles.wxs
  #
  # ${LIGHT} -ext WixUIExtension -ext WixUtilExtension             \
  #   -sval -o $@ cryptol.wixobj allfiles.wixobj
