name: Main workflow
on: [push]
jobs:
  test:
    name: Test windows
    runs-on: windows-latest
    steps:
      - uses: haskell-ci/setup@master
        with:
          ghc-version: 8.8.3
          cabal-version: 3.0.0.0
      - run: |
          cabal user-config diff
