name: Main workflow
on: [push]
jobs:
  things:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p some/directory/tree
          echo "content" > some/directory/tree/foo.txt

      - uses: actions/upload-artifact@v1
        with:
          name: some-artifact
          path: some
